import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "./public/manifest.json",
  generator: "Next.js",
  authors: [{ name: "Akseli Palmer" }],
  keywords: ["teacher", "student", "school", "education"],
  icons: [
    { rel: "apple-touch-icon", url: "../../public/icons/apple-touch-icon.png" },
    { rel: "shortcut icon", url: "../../public/favicon.ico" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
